### ISSUE TITLE
When can the code be released?

### ISSUE THREAD

**Issue by tairan-w** [pemywei/csanmt#2]
Thanks for your great work. I'm looking forward to learning from it!

**Comment by pemywei** [comment]
Thanks for your attention and sorry for this late reply! The code is still under internal review, so if you're in a hurry, you can email me. I will send you a copy.

**Comment by AIikai** [comment]
It's a great work. Could you share a copy with me too? thank U!  Here is my mail: lk_nlper@foxmail.com
