### ISSUE TITLE
No code?

### ISSUE THREAD

**Issue by tomsbergmanis** [pemywei/csanmt#3]
Hi, 
I just read your paper! Very interesting work, but you have not published any source code. Why so? 
Best, 
Toms

**Comment by pemywei** [comment]
Thanks for your attention! The code is still under internal review, so if you're in a hurry, you can email me. I will send you a copy.

**Comment by tomsbergmanis** [comment]
That would be great: toms.bergmanis@gmail.com

**Comment by buptpriswang** [comment]
very interesting work, could you share a copy with me too? thanks~~ here is my mail: jinglanzhiji@gmail.com

**Comment by tomsbergmanis** [comment]
@pemywei I still haven't received it :)

**Comment by pemywei** [comment]
> jinglanzhiji@gmail.com

Sure, I have emailed you!

**Comment by pemywei** [comment]
> @pemywei I still haven't received it :)

I just tried the second time. Do you get it now?

**Comment by joeforan76** [comment]
I would love to recieve a copy of the source code too! throwaway.220531@gmail.com

**Comment by tomsbergmanis** [comment]
> [pemywei](/pemywei)

Got it! Thanks!

**Comment by buptpriswang** [comment]
> > [jinglanzhiji@gmail.com](mailto:jinglanzhiji@gmail.com)
> 
> Sure, I have emailed you!

Got it! Thanks a lot !

**Comment by rgwt123** [comment]
> Thanks for your attention! The code is still under internal review, so if you're in a hurry, you can email me. I will send you a copy.

I would love to receive a copy of the source code too! 
email: rgwt1234@gmail.com

**Comment by jucho2725** [comment]
Great work, I'd love to receive a copy of the source code! Thanks in advance. 
cju2725@gmail.com

**Comment by sathishreddy** [comment]
Great work Xiangpeng Wei, Could you please send a copy of code to sathish.indurthi@gmail.com. Thanks in advance.

**Comment by jzhang38** [comment]
peiyuan_zhang@mymail.sutd.edu.sg 
Thank you so much!

**Comment by hrwise-nlp** [comment]
I would love to receive a copy of the source code too! anyone help?? [hongru.carrywang@gmail.com](mailto:hongru.carrywang@gmail.com)

**Comment by yejh123** [comment]
I would love to receive a copy of the source code too! Please send to 13302908246ye@gmail.com
Thanks!
