### ISSUE TITLE
Could you share the code

### ISSUE THREAD

**Issue by dantengdekaoya** [pemywei/csanmt#6]
hello, there is only readme instruction and no codes below, could you share the code? thank you

**Comment by ShunchiZhang** [comment]
> hello, there is only readme instruction and no codes below, could you share the code? thank you

According to past issues (e.g. #3), the code is under internal review. We could leave an email here then the author might send us a copy :)

**Comment by dantengdekaoya** [comment]
> 

understood, thanks :)

**Comment by dantengdekaoya** [comment]
> > hello, there is only readme instruction and no codes below, could you share the code? thank you
> 
> According to past issues (e.g. #3), the code is under internal review. We could leave an email here then the author might send us a copy :)

understood, thanks :) @pemywei I would love to receive a copy of the source code too! zhangyudanny@gmail.com

**Comment by shiyanlou-015555** [comment]
Thank you,I would love to receive a copy of the source code too! 20215227120@stu.suda.edu.cn

**Comment by Liyyy2122** [comment]
Thank you, could you send me a copy？ 51205901077@stu.ecnu.edu.cn
