### ISSUE TITLE
I hope the author can share the code, thank you very much

### ISSUE THREAD

**Issue by yyxx1997** [pemywei/csanmt#8]
I hope the author can give a code example of the sampling part of MGRC, preferably the pytorch version. I am very confused about this part, and my tensorflow ability is very poor. Thank you very much. My email is: yyxx20150909@163.com

**Comment by zhuyl96** [comment]
I would be grateful to the author for sharing the source code, my email is: zhuyl1996@qq.com

**Comment by cyy489** [comment]
If the author could share the source code, I’d be very grateful. Either pytorch or tensorflow version are OK. I am very interested in this work. Thanks, thanks a lot. My email is: 2446172093@qq.com

**Comment by pemywei** [comment]
> I would be grateful to the author for sharing the source code, my email is: [zhuyl1996@qq.com](mailto:zhuyl1996@qq.com)

550 Mailbox unavailable or access denied. Pls provide other email adresses.

**Comment by zhuyl96** [comment]
> > I would be grateful to the author for sharing the source code, my email is: [zhuyl1996@qq.com](mailto:zhuyl1996@qq.com)
> 
> 550 Mailbox unavailable or access denied. Pls provide other email adresses.

Sorry... this is the correct email: ylzhu1996@qq.com. Thank you!

**Comment by cordercorder** [comment]
Amazing work!
Could you share the source code with me? I would prefer to receive the pytorch version if both pytorch and tensorflow implementation exist.  Thanks in advance.
My email is rrjin98@foxmail.com.

**Comment by nlpxxx** [comment]
Great work! 
I am very interested in your work. Could you share the source code with me? Preferably the pytorch version.  Thanks a lot!
my email is: 645047176@qq.com.

**Comment by qy826687054** [comment]
Pretty well work!
Could you share me your source code? I am  very grateful for your kindness~
my email is: 826687054@qq.com

**Comment by srmiao** [comment]
Amazing work!
Could you share me your source code? I really appreciate you being able to share the code with me~
my email is 982405373@qq.com

**Comment by Poeroz** [comment]
Hi, thanks for your great work. Could you share the PyTorch source code with me? My email is poeroz1204@gmail.com. Thanks a lot!

**Comment by TS-Liu** [comment]
Great work!
I am very interested in your work. Could you share the PyTorch source code with me?. Thanks a lot!
my email is: [2269783129@qq.com](mailto:2269783129@qq.com).

**Comment by WaltzofLeave** [comment]
Really great work!
I am very interested in your work. Could you share the PyTorch source code with me? Thanks a lot!
my email is: 1144504869@qq.com

**Comment by dantengdekaoya** [comment]
I am very interested in your work. Could you share the PyTorch source code with me? Thanks a lot!
my email is: 442613317@qq.com

**Comment by 13347248340** [comment]
What a greatful work!
I am very interested in your work. Could you please share the PyTorch source code with me? Thanks in advance!
My email is: 1132164774@qq.com

**Comment by 123wanyu** [comment]
What a greatful work!
Could you share me your source code? I really appreciate you being able to share the code with me~Thanks in advance!
My email is:wanyu778@gmail.com

**Comment by feiyuehchen** [comment]
Great work!
I'm interested in your work and would like to try it in my project. Could you share the PyTorch source code with me? I will be very appreciate it.
my email is: [feiyuehchen@gmail.com](mailto:feiyuehchen@gmail.com)

**Comment by Jhansoll** [comment]
That's a great study, can you share the code with me? I'll wait for it! Thanks a lot!
My email is : 624jhs@gmail.com

**Comment by rick-lzr** [comment]
Thanks for your great study. Can you share the code with me? Thanks a lot!
My email is : 936332553@qq.com

**Comment by JunchengYao** [comment]
Great work!
I am very interested in your work. Could you share the source code with me? Thanks a lot!
my email is: junchengyao@outlook.com

**Comment by vhientran** [comment]
@pemywei Could you please share your source code with us? Thanks!

**Comment by UnderController** [comment]
Pretty well work!
Could you share me your source code? I am very grateful for your kindness~
my email is: [1185913859@qq.com](mailto:1185913859@qq.com)

**Comment by bl-sun** [comment]
Pretty well work!
Could you share me your source code? I am very grateful for your kindness~
my email is: [sunbaolei99@qq.com](mailto:sunbaolei99@qq.com)

**Comment by KLZXHui** [comment]
I am very interested in the author's work on NLP data enhancement, and I hope the author can provide the code I would appreciate it, thank you! My email is skz192@outlook.com

**Comment by pemywei** [comment]
Done.

**Comment by zhang-jinyi** [comment]
> Hi, thanks for your great work. Could you share the PyTorch source code with me? My email is [poeroz1204@gmail.com](mailto:poeroz1204@gmail.com). Thanks a lot!

@Poeroz @vhientran @UnderController @TS-Liu @pemywei @KLZXHui @bl-sun @Jhansoll @vhientran @dantengdekaoya 

Excuse the interruption, but would it be possible to provide me with a code sample for academic research purposes? I would greatly appreciate your assistance. Thank you!
My email is: zhang-jinyi@outlook.com
